ORG 1000H
TABLA DB DUP(2,4,6,8,10,12,14,16,18,20)
FIN DB ?
TOTAL DB ?
MAX DB 13
ORG 2000H; contar los mayores a MAX y guardarla en total
MOV AL, 0
MOV CL, OFFSET FIN-OFFSET TABLA
MOV BX, OFFSET TABLA
MOV DL, MAX
COMPARAR: CMP DL, [BX]
JS SALTO
INC AL; SI NO HAY SIGNO ES PORQ SON IGUALES O [BX] ES MENOR
SALTO: INC Bl
DEC CL
JNZ COMPARAR; REPITO HASTA ANALIZAR TODOS LOS ELEMENTOS
MOV BX, OFFSET TOTAL
MOV [BX], AL
HLT
END

